leftnav:
- identifier: 4a8e2dd3-b187-074e-9166-46f30bff2fda
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 0b738c60-4d01-39ac-c68a-2a460c5de906
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 118a5bc0-6690-0c94-fe7c-6567c79840a9
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: e9bda4ec-888a-6d27-55a1-21f044d429c7
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 40
- identifier: dd51e754-29e1-208d-6487-ee0d1ef3ddb5
  name: Assignments
  url: /pages/assignments
  weight: 50
